name 'test'
maintainer 'Dave'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures tomcat 8 on centos-7'
long_description 'Installs/Configures tomcat 8 on centos-7 on vagrant via kitchen'
version '0.1.1'
